spring:
  application:
    name: Agent
  datasource:
    url: jdbc:postgresql://localhost:5432/rag_db
    username: zq
    password: zq2892294059
    driver-class-name: org.postgresql.Driver
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
      timeout: 3000ms

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.library.agent.entity
  configuration:
    map-underscore-to-camel-case: true

minio:
  endpoint: http://localhost:9000
  access-key: admin
  secret-key: zq2892294059
  bucket: rag-bucket

bailian:
  api-key: sk-0de87aaea6234b70b902fc5c1dcdc253
  embedding-url: https://dashscope.aliyuncs.com/compatible-mode/v1/embeddings
  embedding-model: text-embedding-v4
  tool-chat-url: https://dashscope.aliyuncs.com/compatible-mode/v1
  chat-url: https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions
  chat-model: qwen-plus
server:
  port: 8088

rocketmq:
  name-server: 127.0.0.1:9876
  producer:
    group: agent-producer-group
    send-message-timeout: 3000

auth:
  token:
    expire-seconds: 604800
    redis-key-prefix: "agent:login:token:"
